// cSpell:ignore alverata configuracion gestion
/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package screens;

import screens.custom.CambiarIU;

/**
 *
 * @author tutaa
 */
public class GestionLibros extends javax.swing.JFrame {

        /**
         * Creates new form Principal
         */
        public GestionLibros() {
                initComponents();
                configuracionPantalla();
        }

        /**
         * This method is called from within the constructor to initialize the
         * form. WARNING: Do NOT modify this code. The content of this method is
         * always regenerated by the Form Editor.
         */
        @SuppressWarnings("unchecked")
        // <editor-fold defaultstate="collapsed" desc="Generated
        // <editor-fold defaultstate="collapsed" desc="Generated
        // <editor-fold defaultstate="collapsed" desc="Generated
        // Code">//GEN-BEGIN:initComponents
        private void initComponents() {

                jPanel1 = new javax.swing.JPanel();
                imgBack = new javax.swing.JLabel();
                lbLibros = new javax.swing.JLabel();
                lbTitulo = new javax.swing.JLabel();
                tfTitulo = new javax.swing.JTextField();
                lbAutor = new javax.swing.JLabel();
                tfAutor = new javax.swing.JTextField();
                lbGenero = new javax.swing.JLabel();
                cbGenero = new javax.swing.JComboBox<>();
                lbEditorial = new javax.swing.JLabel();
                tfEditorial = new javax.swing.JTextField();
                lbNumeroPaginas = new javax.swing.JLabel();
                tfNumeroPaginas = new javax.swing.JTextField();
                lbIdioma = new javax.swing.JLabel();
                cbIdioma = new javax.swing.JComboBox<>();
                lbSinopsis = new javax.swing.JLabel();
                spSinopsis = new javax.swing.JScrollPane();
                taSinopsis = new javax.swing.JTextArea();
                lbEstado = new javax.swing.JLabel();
                tfEstado = new javax.swing.JTextField();
                lbNumeroCopias = new javax.swing.JLabel();
                tfNumeroCopias = new javax.swing.JTextField();
                btnCrearLibro = new javax.swing.JButton();
                spTabla = new javax.swing.JScrollPane();
                tTablaLibros = new javax.swing.JTable();
                btnModificarLibro = new javax.swing.JButton();
                btnEliminarLibro = new javax.swing.JButton();

                setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

                jPanel1.setBackground(new java.awt.Color(249, 244, 239));
                jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

                imgBack.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/img/back.png"))); // NOI18N
                imgBack.addMouseListener(new java.awt.event.MouseAdapter() {
                        public void mouseClicked(java.awt.event.MouseEvent evt) {
                                imgBackMouseClicked(evt);
                        }

                        public void mouseEntered(java.awt.event.MouseEvent evt) {
                                imgBackMouseEntered(evt);
                        }

                        public void mouseExited(java.awt.event.MouseEvent evt) {
                                imgBackMouseExited(evt);
                        }
                });
                jPanel1.add(imgBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

                lbLibros.setFont(new java.awt.Font("AlverataIrregular-Bold", 0, 80)); // NOI18N
                lbLibros.setForeground(new java.awt.Color(2, 8, 38));
                lbLibros.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
                lbLibros.setText("LIBROS");
                jPanel1.add(lbLibros, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 20, 850, -1));

                lbTitulo.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
                lbTitulo.setForeground(new java.awt.Color(2, 8, 38));
                lbTitulo.setText("TÍTULO:");
                jPanel1.add(lbTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 130, 110, -1));

                tfTitulo.setBackground(new java.awt.Color(234, 221, 207));
                tfTitulo.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
                tfTitulo.setForeground(new java.awt.Color(2, 8, 38));
                jPanel1.add(tfTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 130, 210, -1));

                lbAutor.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
                lbAutor.setForeground(new java.awt.Color(2, 8, 38));
                lbAutor.setText("AUTOR:");
                jPanel1.add(lbAutor, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 170, 110, -1));

                tfAutor.setBackground(new java.awt.Color(234, 221, 207));
                tfAutor.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
                tfAutor.setForeground(new java.awt.Color(2, 8, 38));
                jPanel1.add(tfAutor, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 170, 210, -1));

                lbGenero.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
                lbGenero.setForeground(new java.awt.Color(2, 8, 38));
                lbGenero.setText("GÉNERO:");
                jPanel1.add(lbGenero, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 210, 110, -1));

                cbGenero.setBackground(new java.awt.Color(234, 221, 207));
                cbGenero.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
                cbGenero.setForeground(new java.awt.Color(2, 8, 38));
                cbGenero.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Narrativa", "Poesía", "Drama",
                                "Ensayo", "Épica", "Lírica", "Cuento", "Novela", "Fábula", "Mito", "Leyenda",
                                "Autobiografía", "Biografía", "Crónica", "Epopeya", "Sátira", "Oratoria", "Diario",
                                "Epístola", "Tragedia", "Otro" }));
                cbGenero.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                cbGeneroActionPerformed(evt);
                        }
                });
                jPanel1.add(cbGenero, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 210, 210, -1));

                lbEditorial.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
                lbEditorial.setForeground(new java.awt.Color(2, 8, 38));
                lbEditorial.setText("EDITORIAL:");
                jPanel1.add(lbEditorial, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 250, 110, -1));

                tfEditorial.setBackground(new java.awt.Color(234, 221, 207));
                tfEditorial.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
                tfEditorial.setForeground(new java.awt.Color(2, 8, 38));
                jPanel1.add(tfEditorial, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 250, 210, -1));

                lbNumeroPaginas.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
                lbNumeroPaginas.setForeground(new java.awt.Color(2, 8, 38));
                lbNumeroPaginas.setText("NÚMERO PÁGINAS:");
                jPanel1.add(lbNumeroPaginas, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 290, 180, -1));

                tfNumeroPaginas.setBackground(new java.awt.Color(234, 221, 207));
                tfNumeroPaginas.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
                tfNumeroPaginas.setForeground(new java.awt.Color(2, 8, 38));
                jPanel1.add(tfNumeroPaginas, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 290, 130, -1));

                lbIdioma.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
                lbIdioma.setForeground(new java.awt.Color(2, 8, 38));
                lbIdioma.setText("IDIOMA:");
                jPanel1.add(lbIdioma, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 330, 110, -1));

                cbIdioma.setBackground(new java.awt.Color(234, 221, 207));
                cbIdioma.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
                cbIdioma.setForeground(new java.awt.Color(2, 8, 38));
                cbIdioma.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Español", "Inglés", "Mandarín",
                                "Francés", "Árabe", "Ruso", "Alemán", "Japonés", "Hindi", "Portugués", "Italiano",
                                "Coreano", "Bengalí", "Turco", "Persa", "Suajili", "Holandés", "Vietnamita", "Polaco",
                                "Tailandés", "Otro" }));
                cbIdioma.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                cbIdiomaActionPerformed(evt);
                        }
                });
                jPanel1.add(cbIdioma, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 330, 210, -1));

                lbSinopsis.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
                lbSinopsis.setForeground(new java.awt.Color(2, 8, 38));
                lbSinopsis.setText("SINOPSIS:");
                jPanel1.add(lbSinopsis, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 370, 110, -1));

                taSinopsis.setBackground(new java.awt.Color(234, 221, 207));
                taSinopsis.setColumns(20);
                taSinopsis.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
                taSinopsis.setForeground(new java.awt.Color(2, 8, 38));
                taSinopsis.setRows(5);
                spSinopsis.setViewportView(taSinopsis);

                jPanel1.add(spSinopsis, new org.netbeans.lib.awtextra.AbsoluteConstraints(94, 410, 310, 100));

                lbEstado.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
                lbEstado.setForeground(new java.awt.Color(2, 8, 38));
                lbEstado.setText("ESTADO:");
                jPanel1.add(lbEstado, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 530, 110, -1));

                tfEstado.setBackground(new java.awt.Color(234, 221, 207));
                tfEstado.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
                tfEstado.setForeground(new java.awt.Color(2, 8, 38));
                jPanel1.add(tfEstado, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 530, 210, -1));

                lbNumeroCopias.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
                lbNumeroCopias.setForeground(new java.awt.Color(2, 8, 38));
                lbNumeroCopias.setText("NÚMERO COPIAS:");
                jPanel1.add(lbNumeroCopias, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 570, 160, -1));

                tfNumeroCopias.setBackground(new java.awt.Color(234, 221, 207));
                tfNumeroCopias.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
                tfNumeroCopias.setForeground(new java.awt.Color(2, 8, 38));
                jPanel1.add(tfNumeroCopias, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 570, 130, -1));

                btnCrearLibro.setBackground(new java.awt.Color(140, 120, 81));
                btnCrearLibro.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
                btnCrearLibro.setForeground(new java.awt.Color(255, 255, 254));
                btnCrearLibro.setText("Registrar Nuevo Libro");
                btnCrearLibro.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                btnCrearLibroActionPerformed(evt);
                        }
                });
                jPanel1.add(btnCrearLibro, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 630, -1, -1));

                tTablaLibros.setBackground(new java.awt.Color(234, 221, 207));
                tTablaLibros.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
                tTablaLibros.setForeground(new java.awt.Color(2, 8, 38));
                tTablaLibros.setModel(new javax.swing.table.DefaultTableModel(
                                new Object[][] {
                                                { null, null, null, null },
                                                { null, null, null, null },
                                                { null, null, null, null },
                                                { null, null, null, null }
                                },
                                new String[] {
                                                "Title 1", "Title 2", "Title 3", "Title 4"
                                }));
                spTabla.setViewportView(tTablaLibros);

                jPanel1.add(spTabla, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 130, 370, 470));

                btnModificarLibro.setBackground(new java.awt.Color(140, 120, 81));
                btnModificarLibro.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
                btnModificarLibro.setForeground(new java.awt.Color(255, 255, 254));
                btnModificarLibro.setText("Modificar Libro");
                btnModificarLibro.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                btnModificarLibroActionPerformed(evt);
                        }
                });
                jPanel1.add(btnModificarLibro, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 630, -1, -1));

                btnEliminarLibro.setBackground(new java.awt.Color(140, 120, 81));
                btnEliminarLibro.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
                btnEliminarLibro.setForeground(new java.awt.Color(255, 255, 254));
                btnEliminarLibro.setText("Eliminar Libro");
                btnEliminarLibro.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                btnEliminarLibroActionPerformed(evt);
                        }
                });
                jPanel1.add(btnEliminarLibro, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 630, -1, -1));

                javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
                getContentPane().setLayout(layout);
                layout.setHorizontalGroup(
                                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE));
                layout.setVerticalGroup(
                                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 694,
                                                                Short.MAX_VALUE));

                pack();
        }// </editor-fold>//GEN-END:initComponents

        private void imgBackMouseClicked(java.awt.event.MouseEvent evt) {
                Principal p = new Principal();
                p.setVisible(true);
                this.setVisible(false);

        }

        private void imgBackMouseEntered(java.awt.event.MouseEvent evt) {
                CambiarIU.setImageLabel(imgBack, "src/resources/img/backHover.png");

        }

        private void imgBackMouseExited(java.awt.event.MouseEvent evt) {
                CambiarIU.setImageLabel(imgBack, "src/resources/img/back.png");

        }

        private void btnEliminarLibroActionPerformed(java.awt.event.ActionEvent evt) {

        }

        private void btnCrearLibroActionPerformed(java.awt.event.ActionEvent evt) {

        }

        private void btnModificarLibroActionPerformed(java.awt.event.ActionEvent evt) {
                ModificarLibro ml = new ModificarLibro();
                ml.setVisible(true);
                this.setVisible(false);

        }

        private void cbGeneroActionPerformed(java.awt.event.ActionEvent evt) {

        }

        private void cbIdiomaActionPerformed(java.awt.event.ActionEvent evt) {

        }

        private void configuracionPantalla() {
                this.setTitle("Gestión Libros");
                this.setResizable(false);
                this.setLocationRelativeTo(null);

        }

        /**
         * @param args the command line arguments
         */
        public static void main(String args[]) {
                /* Set the Nimbus look and feel */
                // <editor-fold defaultstate="collapsed" desc=" Look and feel setting code
                // (optional) ">
                /*
                 * If Nimbus (introduced in Java SE 6) is not available, stay with the default
                 * look and feel.
                 * For details see
                 * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
                 */
                try {
                        for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager
                                        .getInstalledLookAndFeels()) {
                                if ("Nimbus".equals(info.getName())) {
                                        javax.swing.UIManager.setLookAndFeel(info.getClassName());
                                        break;
                                }
                        }
                } catch (ClassNotFoundException ex) {
                        java.util.logging.Logger.getLogger(GestionLibros.class.getName())
                                        .log(java.util.logging.Level.SEVERE, null, ex);
                } catch (InstantiationException ex) {
                        java.util.logging.Logger.getLogger(GestionLibros.class.getName())
                                        .log(java.util.logging.Level.SEVERE, null, ex);
                } catch (IllegalAccessException ex) {
                        java.util.logging.Logger.getLogger(GestionLibros.class.getName())
                                        .log(java.util.logging.Level.SEVERE, null, ex);
                } catch (javax.swing.UnsupportedLookAndFeelException ex) {
                        java.util.logging.Logger.getLogger(GestionLibros.class.getName())
                                        .log(java.util.logging.Level.SEVERE, null, ex);
                }
                // </editor-fold>
                // </editor-fold>
                // </editor-fold>
                // </editor-fold>

                /* Create and display the form */
                java.awt.EventQueue.invokeLater(new Runnable() {
                        public void run() {
                                new GestionLibros().setVisible(true);
                        }
                });
        }

        // Variables declaration - do not modify//GEN-BEGIN:variables
        private javax.swing.JButton btnCrearLibro;
        private javax.swing.JButton btnEliminarLibro;
        private javax.swing.JButton btnModificarLibro;
        private javax.swing.JComboBox<String> cbGenero;
        private javax.swing.JComboBox<String> cbIdioma;
        private javax.swing.JLabel imgBack;
        private javax.swing.JPanel jPanel1;
        private javax.swing.JLabel lbAutor;
        private javax.swing.JLabel lbEditorial;
        private javax.swing.JLabel lbEstado;
        private javax.swing.JLabel lbGenero;
        private javax.swing.JLabel lbIdioma;
        private javax.swing.JLabel lbLibros;
        private javax.swing.JLabel lbNumeroCopias;
        private javax.swing.JLabel lbNumeroPaginas;
        private javax.swing.JLabel lbSinopsis;
        private javax.swing.JLabel lbTitulo;
        private javax.swing.JScrollPane spSinopsis;
        private javax.swing.JScrollPane spTabla;
        private javax.swing.JTable tTablaLibros;
        private javax.swing.JTextArea taSinopsis;
        private javax.swing.JTextField tfAutor;
        private javax.swing.JTextField tfEditorial;
        private javax.swing.JTextField tfEstado;
        private javax.swing.JTextField tfNumeroCopias;
        private javax.swing.JTextField tfNumeroPaginas;
        private javax.swing.JTextField tfTitulo;
        // End of variables declaration//GEN-END:variables
}
