// cSpell:ignore alverata configuracion
/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package screens;

import java.awt.Toolkit;

/**
 *
 * @author tutaa
 */
public class GestionPrestamos extends javax.swing.JFrame {

	/**
	 * Creates new form Principal
	 */
	public GestionPrestamos() {
		initComponents();
		configuracionPantalla();
	}

	/**
	 * This method is called from within the constructor to initialize the
	 * form. WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
	// <editor-fold defaultstate="collapsed" desc="Generated
	// <editor-fold defaultstate="collapsed" desc="Generated
        // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
        private void initComponents() {

                jPanel1 = new javax.swing.JPanel();
                lbPrestamos = new javax.swing.JLabel();
                lbCliente = new javax.swing.JLabel();
                cbCliente = new javax.swing.JComboBox<>();
                lbLibro = new javax.swing.JLabel();
                cbLibro = new javax.swing.JComboBox<>();
                lbFechaDevolucion = new javax.swing.JLabel();
                tfFechaDevolucion = new javax.swing.JTextField();
                btnCrearPrestamo = new javax.swing.JButton();
                spTabla = new javax.swing.JScrollPane();
                tTablaPrestamos = new javax.swing.JTable();
                btnModificarPrestamo = new javax.swing.JButton();
                btnEliminarPrestamo = new javax.swing.JButton();

                setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

                jPanel1.setBackground(new java.awt.Color(249, 244, 239));
                jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

                lbPrestamos.setFont(new java.awt.Font("AlverataIrregular-Bold", 0, 80)); // NOI18N
                lbPrestamos.setForeground(new java.awt.Color(2, 8, 38));
                lbPrestamos.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
                lbPrestamos.setText("PRESTAMOS");
                jPanel1.add(lbPrestamos, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 20, 850, -1));

                lbCliente.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
                lbCliente.setForeground(new java.awt.Color(2, 8, 38));
                lbCliente.setText("CLIENTE:");
                jPanel1.add(lbCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 210, 110, -1));

                cbCliente.setBackground(new java.awt.Color(234, 221, 207));
                cbCliente.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
                cbCliente.setForeground(new java.awt.Color(2, 8, 38));
                cbCliente.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Narrativa", "Poesía", "Drama", "Ensayo", "Épica", "Lírica", "Cuento", "Novela", "Fábula", "Mito", "Leyenda", "Autobiografía", "Biografía", "Crónica", "Epopeya", "Sátira", "Oratoria", "Diario", "Epístola", "Tragedia", "Otro" }));
                jPanel1.add(cbCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 210, 210, -1));

                lbLibro.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
                lbLibro.setForeground(new java.awt.Color(2, 8, 38));
                lbLibro.setText("LIBRO:");
                jPanel1.add(lbLibro, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 250, 110, -1));

                cbLibro.setBackground(new java.awt.Color(234, 221, 207));
                cbLibro.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
                cbLibro.setForeground(new java.awt.Color(2, 8, 38));
                cbLibro.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Narrativa", "Poesía", "Drama", "Ensayo", "Épica", "Lírica", "Cuento", "Novela", "Fábula", "Mito", "Leyenda", "Autobiografía", "Biografía", "Crónica", "Epopeya", "Sátira", "Oratoria", "Diario", "Epístola", "Tragedia", "Otro" }));
                jPanel1.add(cbLibro, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 250, 210, -1));

                lbFechaDevolucion.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
                lbFechaDevolucion.setForeground(new java.awt.Color(2, 8, 38));
                lbFechaDevolucion.setText("FECHA DEVOLUCIÓN:");
                jPanel1.add(lbFechaDevolucion, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 290, 190, -1));

                tfFechaDevolucion.setBackground(new java.awt.Color(234, 221, 207));
                tfFechaDevolucion.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
                tfFechaDevolucion.setForeground(new java.awt.Color(2, 8, 38));
                jPanel1.add(tfFechaDevolucion, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 290, 130, -1));

                btnCrearPrestamo.setBackground(new java.awt.Color(140, 120, 81));
                btnCrearPrestamo.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
                btnCrearPrestamo.setForeground(new java.awt.Color(255, 255, 254));
                btnCrearPrestamo.setText("Crear Nuevo Prestamo");
                btnCrearPrestamo.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                btnCrearPrestamoActionPerformed(evt);
                        }
                });
                jPanel1.add(btnCrearPrestamo, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 330, -1, -1));

                tTablaPrestamos.setBackground(new java.awt.Color(234, 221, 207));
                tTablaPrestamos.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
                tTablaPrestamos.setForeground(new java.awt.Color(2, 8, 38));
                tTablaPrestamos.setModel(new javax.swing.table.DefaultTableModel(
                        new Object [][] {
                                {null, null, null, null},
                                {null, null, null, null},
                                {null, null, null, null},
                                {null, null, null, null}
                        },
                        new String [] {
                                "Title 1", "Title 2", "Title 3", "Title 4"
                        }
                ));
                spTabla.setViewportView(tTablaPrestamos);

                jPanel1.add(spTabla, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 130, 370, 340));

                btnModificarPrestamo.setBackground(new java.awt.Color(140, 120, 81));
                btnModificarPrestamo.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
                btnModificarPrestamo.setForeground(new java.awt.Color(255, 255, 254));
                btnModificarPrestamo.setText("Modificar Prestamo");
                btnModificarPrestamo.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                btnModificarPrestamoActionPerformed(evt);
                        }
                });
                jPanel1.add(btnModificarPrestamo, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 480, -1, -1));

                btnEliminarPrestamo.setBackground(new java.awt.Color(140, 120, 81));
                btnEliminarPrestamo.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
                btnEliminarPrestamo.setForeground(new java.awt.Color(255, 255, 254));
                btnEliminarPrestamo.setText("Eliminar Prestamo");
                btnEliminarPrestamo.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                btnEliminarPrestamoActionPerformed(evt);
                        }
                });
                jPanel1.add(btnEliminarPrestamo, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 480, -1, -1));

                javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
                getContentPane().setLayout(layout);
                layout.setHorizontalGroup(
                        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                );
                layout.setVerticalGroup(
                        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 563, Short.MAX_VALUE)
                );

                pack();
        }// </editor-fold>//GEN-END:initComponents

        private void btnModificarPrestamoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarPrestamoActionPerformed
                // TODO add your handling code here:
        }//GEN-LAST:event_btnModificarPrestamoActionPerformed

        private void btnCrearPrestamoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCrearPrestamoActionPerformed
                // TODO add your handling code here:
        }//GEN-LAST:event_btnCrearPrestamoActionPerformed

        private void btnEliminarPrestamoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarPrestamoActionPerformed
                // TODO add your handling code here:
        }//GEN-LAST:event_btnEliminarPrestamoActionPerformed

	private void configuracionPantalla() {
		// TODO: PONER NOMBRE PANTALLA
		this.setTitle("--");
		this.setResizable(false);
		this.setLocationRelativeTo(null);
		// TODO: PONER ICONO APP
		this.setIconImage(Toolkit.getDefaultToolkit()
				.getImage(getClass().getResource("/img/icon.png")));

	}

	private void btnAceptarActionPerformed(java.awt.event.ActionEvent evt) {

	}

	/**
	 * @param args the command line arguments
	 */
	public static void main(String args[]) {
		/* Set the Nimbus look and feel */
		// <editor-fold defaultstate="collapsed" desc=" Look and feel setting code
		// (optional) ">
		/*
		 * If Nimbus (introduced in Java SE 6) is not available, stay with the default
		 * look and feel.
		 * For details see
		 * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
		 */
		try {
			for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
				if ("Nimbus".equals(info.getName())) {
					javax.swing.UIManager.setLookAndFeel(info.getClassName());
					break;
				}
			}
		} catch (ClassNotFoundException ex) {
			java.util.logging.Logger.getLogger(GestionPrestamos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (InstantiationException ex) {
			java.util.logging.Logger.getLogger(GestionPrestamos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (IllegalAccessException ex) {
			java.util.logging.Logger.getLogger(GestionPrestamos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (javax.swing.UnsupportedLookAndFeelException ex) {
			java.util.logging.Logger.getLogger(GestionPrestamos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		}
		// </editor-fold>
		// </editor-fold>
		// </editor-fold>
		// </editor-fold>

		/* Create and display the form */
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				new GestionPrestamos().setVisible(true);
			}
		});
	}

        // Variables declaration - do not modify//GEN-BEGIN:variables
        private javax.swing.JButton btnCrearPrestamo;
        private javax.swing.JButton btnEliminarPrestamo;
        private javax.swing.JButton btnModificarPrestamo;
        private javax.swing.JComboBox<String> cbCliente;
        private javax.swing.JComboBox<String> cbLibro;
        private javax.swing.JPanel jPanel1;
        private javax.swing.JLabel lbCliente;
        private javax.swing.JLabel lbFechaDevolucion;
        private javax.swing.JLabel lbLibro;
        private javax.swing.JLabel lbPrestamos;
        private javax.swing.JScrollPane spTabla;
        private javax.swing.JTable tTablaPrestamos;
        private javax.swing.JTextField tfFechaDevolucion;
        // End of variables declaration//GEN-END:variables
}
