// cSpell:ignore alverata configuracion direccion gestion telefono boton operacion
/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package screens;

import java.sql.SQLException;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;

import javax.swing.JOptionPane;

import classes.OperacionCRUD;
import screens.custom.CambiarIU;
import screens.custom.ObtenerIU;

/**
 *
 * @author tutaa
 */
public class GestionClientes extends javax.swing.JFrame {
        public static int idClienteSeleccionado = -1;

        /**
         * Creates new form Principal
         */
        public GestionClientes() {
                initComponents();
                configuracionPantalla();
        }

        /**
         * This method is called from within the constructor to initialize the
         * form. WARNING: Do NOT modify this code. The content of this method is
         * always regenerated by the Form Editor.
         */
        @SuppressWarnings("unchecked")
        // <editor-fold defaultstate="collapsed" desc="Generated
        // <editor-fold defaultstate="collapsed" desc="Generated
        // <editor-fold defaultstate="collapsed" desc="Generated
        // <editor-fold defaultstate="collapsed" desc="Generated
        // <editor-fold defaultstate="collapsed" desc="Generated
        // Code">//GEN-BEGIN:initComponents
        private void initComponents() {

                jPanel1 = new javax.swing.JPanel();
                imgBack = new javax.swing.JLabel();
                lbClientes = new javax.swing.JLabel();
                lbNombre = new javax.swing.JLabel();
                tfNombre = new javax.swing.JTextField();
                lbDireccion = new javax.swing.JLabel();
                tfDireccion = new javax.swing.JTextField();
                lbTelefono = new javax.swing.JLabel();
                tfTelefono = new javax.swing.JTextField();
                lbEmail = new javax.swing.JLabel();
                tfEmail = new javax.swing.JTextField();
                btnCrearCliente = new javax.swing.JButton();
                spTabla = new javax.swing.JScrollPane();
                tTablaClientes = new javax.swing.JTable();
                btnModificarCliente = new javax.swing.JButton();
                btnEliminarCliente = new javax.swing.JButton();

                setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

                jPanel1.setBackground(new java.awt.Color(249, 244, 239));
                jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

                imgBack.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/img/back.png"))); // NOI18N
                imgBack.addMouseListener(new java.awt.event.MouseAdapter() {
                        public void mouseClicked(java.awt.event.MouseEvent evt) {
                                imgBackMouseClicked(evt);
                        }

                        public void mouseEntered(java.awt.event.MouseEvent evt) {
                                imgBackMouseEntered(evt);
                        }

                        public void mouseExited(java.awt.event.MouseEvent evt) {
                                imgBackMouseExited(evt);
                        }
                });
                jPanel1.add(imgBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

                lbClientes.setFont(new java.awt.Font("AlverataIrregular-Bold", 0, 80)); // NOI18N
                lbClientes.setForeground(new java.awt.Color(2, 8, 38));
                lbClientes.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
                lbClientes.setText("CLIENTES");
                jPanel1.add(lbClientes, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 20, 850, -1));

                lbNombre.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
                lbNombre.setForeground(new java.awt.Color(2, 8, 38));
                lbNombre.setText("NOMBRE:");
                jPanel1.add(lbNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 160, 110, -1));

                tfNombre.setBackground(new java.awt.Color(234, 221, 207));
                tfNombre.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
                tfNombre.setForeground(new java.awt.Color(2, 8, 38));
                tfNombre.addKeyListener(new java.awt.event.KeyAdapter() {
                        public void keyReleased(java.awt.event.KeyEvent evt) {
                                tfNombreKeyReleased(evt);
                        }
                });
                jPanel1.add(tfNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 160, 210, -1));

                lbDireccion.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
                lbDireccion.setForeground(new java.awt.Color(2, 8, 38));
                lbDireccion.setText("DIRECCIÓN:");
                jPanel1.add(lbDireccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 200, 110, -1));

                tfDireccion.setBackground(new java.awt.Color(234, 221, 207));
                tfDireccion.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
                tfDireccion.setForeground(new java.awt.Color(2, 8, 38));
                tfDireccion.addKeyListener(new java.awt.event.KeyAdapter() {
                        public void keyReleased(java.awt.event.KeyEvent evt) {
                                tfDireccionKeyReleased(evt);
                        }
                });
                jPanel1.add(tfDireccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 200, 210, -1));

                lbTelefono.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
                lbTelefono.setForeground(new java.awt.Color(2, 8, 38));
                lbTelefono.setText("TELÉFONO:");
                jPanel1.add(lbTelefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 240, 110, -1));

                tfTelefono.setBackground(new java.awt.Color(234, 221, 207));
                tfTelefono.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
                tfTelefono.setForeground(new java.awt.Color(2, 8, 38));
                tfTelefono.addKeyListener(new java.awt.event.KeyAdapter() {
                        public void keyReleased(java.awt.event.KeyEvent evt) {
                                tfTelefonoKeyReleased(evt);
                        }
                });
                jPanel1.add(tfTelefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 240, 210, -1));

                lbEmail.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
                lbEmail.setForeground(new java.awt.Color(2, 8, 38));
                lbEmail.setText("EMAIL:");
                jPanel1.add(lbEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 280, 110, -1));

                tfEmail.setBackground(new java.awt.Color(234, 221, 207));
                tfEmail.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
                tfEmail.setForeground(new java.awt.Color(2, 8, 38));
                tfEmail.addKeyListener(new java.awt.event.KeyAdapter() {
                        public void keyReleased(java.awt.event.KeyEvent evt) {
                                tfEmailKeyReleased(evt);
                        }
                });
                jPanel1.add(tfEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 280, 210, -1));

                btnCrearCliente.setBackground(new java.awt.Color(140, 120, 81));
                btnCrearCliente.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
                btnCrearCliente.setForeground(new java.awt.Color(255, 255, 254));
                btnCrearCliente.setText("Crear Nuevo Cliente");
                btnCrearCliente.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                btnCrearClienteActionPerformed(evt);
                        }
                });
                jPanel1.add(btnCrearCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 330, -1, -1));

                tTablaClientes.setBackground(new java.awt.Color(234, 221, 207));
                tTablaClientes.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
                tTablaClientes.setForeground(new java.awt.Color(2, 8, 38));
                tTablaClientes.setModel(new javax.swing.table.DefaultTableModel(
                                new Object[][] {
                                                { null, null, null, null },
                                                { null, null, null, null },
                                                { null, null, null, null },
                                                { null, null, null, null }
                                },
                                new String[] {
                                                "Title 1", "Title 2", "Title 3", "Title 4"
                                }));
                tTablaClientes.addMouseListener(new java.awt.event.MouseAdapter() {
                        public void mouseClicked(java.awt.event.MouseEvent evt) {
                                tTablaClientesMouseClicked(evt);
                        }
                });
                spTabla.setViewportView(tTablaClientes);

                jPanel1.add(spTabla, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 130, 370, 340));

                btnModificarCliente.setBackground(new java.awt.Color(140, 120, 81));
                btnModificarCliente.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
                btnModificarCliente.setForeground(new java.awt.Color(255, 255, 254));
                btnModificarCliente.setText("Modificar Cliente");
                btnModificarCliente.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                btnModificarClienteActionPerformed(evt);
                        }
                });
                jPanel1.add(btnModificarCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 480, -1, -1));

                btnEliminarCliente.setBackground(new java.awt.Color(140, 120, 81));
                btnEliminarCliente.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
                btnEliminarCliente.setForeground(new java.awt.Color(255, 255, 254));
                btnEliminarCliente.setText("Eliminar Cliente");
                btnEliminarCliente.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                btnEliminarClienteActionPerformed(evt);
                        }
                });
                jPanel1.add(btnEliminarCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 480, -1, -1));

                javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
                getContentPane().setLayout(layout);
                layout.setHorizontalGroup(
                                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE));
                layout.setVerticalGroup(
                                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 563,
                                                                Short.MAX_VALUE));

                pack();
        }// </editor-fold>//GEN-END:initComponents

        private void tfDireccionKeyReleased(java.awt.event.KeyEvent evt) {
                desactivarBotonCrearNuevoCliente();

        }

        private void tfTelefonoKeyReleased(java.awt.event.KeyEvent evt) {
                desactivarBotonCrearNuevoCliente();

        }

        private void tfEmailKeyReleased(java.awt.event.KeyEvent evt) {
                desactivarBotonCrearNuevoCliente();

        }

        private void tfNombreKeyReleased(java.awt.event.KeyEvent evt) {
                desactivarBotonCrearNuevoCliente();
        }

        private void imgBackMouseClicked(java.awt.event.MouseEvent evt) {
                Principal p = new Principal();
                p.setVisible(true);
                this.setVisible(false);

        }

        private void imgBackMouseEntered(java.awt.event.MouseEvent evt) {
                CambiarIU.setImageLabel(imgBack, "src/resources/img/backHover.png");

        }

        private void imgBackMouseExited(java.awt.event.MouseEvent evt) {
                CambiarIU.setImageLabel(imgBack, "src/resources/img/back.png");

        }

        private void btnModificarClienteActionPerformed(java.awt.event.ActionEvent evt) {
                ModificarCliente mc = new ModificarCliente();
                mc.setVisible(true);
                this.setVisible(false);

        }

        private void btnCrearClienteActionPerformed(java.awt.event.ActionEvent evt) {

                registrarCliente();

        }

        private void btnEliminarClienteActionPerformed(java.awt.event.ActionEvent evt) {
                eliminarIdSeleccionadoTabla();
                llenarTablaClientes();
                desactivarBotonEliminarCliente();
                desactivarBotonModificarCliente();

        }

        private void tTablaClientesMouseClicked(java.awt.event.MouseEvent evt) {
                idClienteSeleccionado = obtenerIdSeleccionadoTabla();
                desactivarBotonEliminarCliente();
                desactivarBotonModificarCliente();
        }

        private void configuracionPantalla() {
                this.setTitle("Gestión Clientes");
                this.setResizable(false);
                this.setLocationRelativeTo(null);
                desactivarBotonCrearNuevoCliente();
                desactivarBotonEliminarCliente();
                desactivarBotonModificarCliente();
                llenarTablaClientes();
        }

        private void desactivarBotonCrearNuevoCliente() {
                boolean camposValidos = ObtenerIU.obtenerLongitudTextoCampo(tfNombre) > 8
                                && ObtenerIU.obtenerLongitudTextoCampo(tfDireccion) > 8
                                && ObtenerIU.obtenerLongitudTextoCampo(tfTelefono) > 8
                                && ObtenerIU.obtenerLongitudTextoCampo(tfEmail) > 15
                                && ObtenerIU.obtenerTextoCampo(tfEmail).contains("@");
                btnCrearCliente.setEnabled(camposValidos);

        }

        private void desactivarBotonModificarCliente() {
                boolean filaSeleccionada = obtenerIdSeleccionadoTabla() != -1;
                btnModificarCliente.setEnabled(filaSeleccionada);

        }

        private void desactivarBotonEliminarCliente() {
                boolean filaSeleccionada = obtenerIdSeleccionadoTabla() != -1;
                btnEliminarCliente.setEnabled(filaSeleccionada);

        }

        private void limpiarCampos() {
                CambiarIU.ponerTextoCampo(tfNombre, "");
                CambiarIU.ponerTextoCampo(tfDireccion, "");
                CambiarIU.ponerTextoCampo(tfTelefono, "");
                CambiarIU.ponerTextoCampo(tfEmail, "");
        }

        private int obtenerIdSeleccionadoTabla() {
                int row = tTablaClientes.getSelectedRow();
                if (row != -1) {
                        return (int) (tTablaClientes.getValueAt(row, 0));
                }
                return -1;
        }

        private void eliminarIdSeleccionadoTabla() {
                try {
                        OperacionCRUD.eliminar(
                                        String.format("delete from clientes where id = %d", idClienteSeleccionado));
                } catch (SQLException e) {
                        JOptionPane.showMessageDialog(null, e);
                }

        }

        private void llenarTablaClientes() {

                String[] columnNames = { "ID", "Nombre", "Direccion", "Telefono", "Email", "Fecha Registro" };
                DefaultTableModel tableModel = new DefaultTableModel(columnNames, 0);

                ArrayList<ArrayList<Object>> listaClientes;
                try {
                        listaClientes = OperacionCRUD.seleccionar("select * from clientes",
                                        new String[] { "id", "nombre", "direccion", "telefono", "email",
                                                        "fecha_registro" });

                        for (ArrayList<Object> fila : listaClientes) {
                                Object[] filaArray = fila.toArray(new Object[0]);
                                tableModel.addRow(filaArray);
                        }
                        tTablaClientes.setModel(tableModel);

                        spTabla.setViewportView(tTablaClientes);
                } catch (SQLException e) {

                        JOptionPane.showMessageDialog(null, e);
                }
        }

        private void registrarCliente() {
                try {
                        String nombre = ObtenerIU.obtenerTextoCampo(tfNombre);
                        String direccion = ObtenerIU.obtenerTextoCampo(tfDireccion);
                        String telefono = ObtenerIU.obtenerTextoCampo(tfTelefono);
                        String email = ObtenerIU.obtenerTextoCampo(tfEmail);
                        OperacionCRUD.actualizar(
                                        String.format("insert into clientes(nombre,direccion,telefono,email) values ('%s','%s','%s','%s')",
                                                        nombre, direccion, telefono, email));
                        String nombreClienteRegistrado = String.format("EL CLIENTE %s HA SIDO REGISTRADO CON ÉXITO.",
                                        ObtenerIU.obtenerTextoCampo(tfNombre).toUpperCase());
                        JOptionPane.showMessageDialog(null, nombreClienteRegistrado);
                        limpiarCampos();
                        llenarTablaClientes();
                        desactivarBotonCrearNuevoCliente();
                } catch (SQLException e) {

                        JOptionPane.showMessageDialog(null, e);
                }

        }

        /**
         * @param args the command line arguments
         */
        public static void main(String args[]) {
                /* Set the Nimbus look and feel */
                // <editor-fold defaultstate="collapsed" desc=" Look and feel setting code
                // (optional) ">
                /*
                 * If Nimbus (introduced in Java SE 6) is not available, stay with the default
                 * look and feel.
                 * For details see
                 * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
                 */
                try {
                        for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager
                                        .getInstalledLookAndFeels()) {
                                if ("Nimbus".equals(info.getName())) {
                                        javax.swing.UIManager.setLookAndFeel(info.getClassName());
                                        break;
                                }
                        }
                } catch (ClassNotFoundException ex) {
                        java.util.logging.Logger.getLogger(GestionClientes.class.getName())
                                        .log(java.util.logging.Level.SEVERE, null, ex);
                } catch (InstantiationException ex) {
                        java.util.logging.Logger.getLogger(GestionClientes.class.getName())
                                        .log(java.util.logging.Level.SEVERE, null, ex);
                } catch (IllegalAccessException ex) {
                        java.util.logging.Logger.getLogger(GestionClientes.class.getName())
                                        .log(java.util.logging.Level.SEVERE, null, ex);
                } catch (javax.swing.UnsupportedLookAndFeelException ex) {
                        java.util.logging.Logger.getLogger(GestionClientes.class.getName())
                                        .log(java.util.logging.Level.SEVERE, null, ex);
                }
                // </editor-fold>
                // </editor-fold>

                /* Create and display the form */
                java.awt.EventQueue.invokeLater(new Runnable() {
                        public void run() {
                                new GestionClientes().setVisible(true);
                        }
                });
        }

        // Variables declaration - do not modify//GEN-BEGIN:variables
        private javax.swing.JButton btnCrearCliente;
        private javax.swing.JButton btnEliminarCliente;
        private javax.swing.JButton btnModificarCliente;
        private javax.swing.JLabel imgBack;
        private javax.swing.JPanel jPanel1;
        private javax.swing.JLabel lbClientes;
        private javax.swing.JLabel lbDireccion;
        private javax.swing.JLabel lbEmail;
        private javax.swing.JLabel lbNombre;
        private javax.swing.JLabel lbTelefono;
        private javax.swing.JScrollPane spTabla;
        private javax.swing.JTable tTablaClientes;
        private javax.swing.JTextField tfDireccion;
        private javax.swing.JTextField tfEmail;
        private javax.swing.JTextField tfNombre;
        private javax.swing.JTextField tfTelefono;
        // End of variables declaration//GEN-END:variables
}
