// cSpell:ignore alverata configuracion devolucion prestamo gestion 
/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package screens;

import java.awt.EventQueue;

import com.formdev.flatlaf.themes.FlatMacDarkLaf;

/**
 *
 * @author tutaa
 */
public class ModificarPrestamo extends javax.swing.JFrame {

        /**
         * Creates new form Principal
         */
        public ModificarPrestamo() {
                initComponents();
                configuracionPantalla();
        }

        /**
         * This method is called from within the constructor to initialize the
         * form. WARNING: Do NOT modify this code. The content of this method is
         * always regenerated by the Form Editor.
         */
        @SuppressWarnings("unchecked")
        // <editor-fold defaultstate="collapsed" desc="Generated
        // <editor-fold defaultstate="collapsed" desc="Generated
        // <editor-fold defaultstate="collapsed" desc="Generated
        // Code">//GEN-BEGIN:initComponents
        private void initComponents() {

                jPanel1 = new javax.swing.JPanel();
                lbBienvenido = new javax.swing.JLabel();
                lbCliente = new javax.swing.JLabel();
                cbCliente = new javax.swing.JComboBox<>();
                lbLibro = new javax.swing.JLabel();
                cbLibro = new javax.swing.JComboBox<>();
                lbFechaDevolucion = new javax.swing.JLabel();
                tfFechaDevolucion = new javax.swing.JTextField();
                btnModificarPrestamo = new javax.swing.JButton();
                lbFechaPrestamo = new javax.swing.JLabel();
                tfFechaPrestamo = new javax.swing.JTextField();
                lbEstado = new javax.swing.JLabel();
                cbEstado = new javax.swing.JComboBox<>();
                btnRegresar = new javax.swing.JButton();

                setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

                jPanel1.setBackground(new java.awt.Color(249, 244, 239));
                jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

                lbBienvenido.setFont(new java.awt.Font("AlverataIrregular-Bold", 0, 50)); // NOI18N
                lbBienvenido.setForeground(new java.awt.Color(2, 8, 38));
                lbBienvenido.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
                lbBienvenido.setText("MODIFICAR PRESTAMO");
                jPanel1.add(lbBienvenido, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 20, 590, -1));

                lbCliente.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
                lbCliente.setForeground(new java.awt.Color(2, 8, 38));
                lbCliente.setText("CLIENTE:");
                jPanel1.add(lbCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 160, 110, -1));

                cbCliente.setBackground(new java.awt.Color(234, 221, 207));
                cbCliente.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
                cbCliente.setForeground(new java.awt.Color(2, 8, 38));
                cbCliente.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Narrativa", "Poesía", "Drama",
                                "Ensayo", "Épica", "Lírica", "Cuento", "Novela", "Fábula", "Mito", "Leyenda",
                                "Autobiografía", "Biografía", "Crónica", "Epopeya", "Sátira", "Oratoria", "Diario",
                                "Epístola", "Tragedia", "Otro" }));
                cbCliente.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                cbClienteActionPerformed(evt);
                        }
                });
                jPanel1.add(cbCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 160, 210, -1));

                lbLibro.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
                lbLibro.setForeground(new java.awt.Color(2, 8, 38));
                lbLibro.setText("LIBRO:");
                jPanel1.add(lbLibro, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 200, 110, -1));

                cbLibro.setBackground(new java.awt.Color(234, 221, 207));
                cbLibro.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
                cbLibro.setForeground(new java.awt.Color(2, 8, 38));
                cbLibro.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Narrativa", "Poesía", "Drama",
                                "Ensayo", "Épica", "Lírica", "Cuento", "Novela", "Fábula", "Mito", "Leyenda",
                                "Autobiografía", "Biografía", "Crónica", "Epopeya", "Sátira", "Oratoria", "Diario",
                                "Epístola", "Tragedia", "Otro" }));
                cbLibro.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                cbLibroActionPerformed(evt);
                        }
                });
                jPanel1.add(cbLibro, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 200, 210, -1));

                lbFechaDevolucion.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
                lbFechaDevolucion.setForeground(new java.awt.Color(2, 8, 38));
                lbFechaDevolucion.setText("FECHA DEVOLUCIÓN:");
                jPanel1.add(lbFechaDevolucion, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 280, 190, -1));

                tfFechaDevolucion.setBackground(new java.awt.Color(234, 221, 207));
                tfFechaDevolucion.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
                tfFechaDevolucion.setForeground(new java.awt.Color(2, 8, 38));
                jPanel1.add(tfFechaDevolucion, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 280, 130, -1));

                btnModificarPrestamo.setBackground(new java.awt.Color(140, 120, 81));
                btnModificarPrestamo.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
                btnModificarPrestamo.setForeground(new java.awt.Color(255, 255, 254));
                btnModificarPrestamo.setText("Modificar Prestamo");
                btnModificarPrestamo.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                btnModificarPrestamoActionPerformed(evt);
                        }
                });
                jPanel1.add(btnModificarPrestamo, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 420, -1, -1));

                lbFechaPrestamo.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
                lbFechaPrestamo.setForeground(new java.awt.Color(2, 8, 38));
                lbFechaPrestamo.setText("FECHA PRESTAMO:");
                jPanel1.add(lbFechaPrestamo, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 240, 190, -1));

                tfFechaPrestamo.setBackground(new java.awt.Color(234, 221, 207));
                tfFechaPrestamo.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
                tfFechaPrestamo.setForeground(new java.awt.Color(2, 8, 38));
                jPanel1.add(tfFechaPrestamo, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 240, 130, -1));

                lbEstado.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
                lbEstado.setForeground(new java.awt.Color(2, 8, 38));
                lbEstado.setText("ESTADO:");
                jPanel1.add(lbEstado, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 320, 110, -1));

                cbEstado.setBackground(new java.awt.Color(234, 221, 207));
                cbEstado.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
                cbEstado.setForeground(new java.awt.Color(2, 8, 38));
                cbEstado.setModel(new javax.swing.DefaultComboBoxModel<>(
                                new String[] { "Pendiente", "Entregado", "Sin Devolver" }));
                cbEstado.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                cbEstadoActionPerformed(evt);
                        }
                });
                jPanel1.add(cbEstado, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 320, 210, -1));

                btnRegresar.setBackground(new java.awt.Color(140, 120, 81));
                btnRegresar.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
                btnRegresar.setForeground(new java.awt.Color(255, 255, 254));
                btnRegresar.setText("Regresar");
                btnRegresar.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                btnRegresarActionPerformed(evt);
                        }
                });
                jPanel1.add(btnRegresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 420, -1, -1));

                javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
                getContentPane().setLayout(layout);
                layout.setHorizontalGroup(
                                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE));
                layout.setVerticalGroup(
                                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 495,
                                                                Short.MAX_VALUE));

                pack();
        }// </editor-fold>//GEN-END:initComponents

        private void btnRegresarActionPerformed(java.awt.event.ActionEvent evt) {
                GestionPrestamos gp = new GestionPrestamos();
                gp.setVisible(true);
                this.setVisible(false);

        }

        private void btnModificarPrestamoActionPerformed(java.awt.event.ActionEvent evt) {
                ModificarPrestamo mp = new ModificarPrestamo();
                mp.setVisible(true);
                this.setVisible(false);

        }

        private void cbClienteActionPerformed(java.awt.event.ActionEvent evt) {

        }

        private void cbLibroActionPerformed(java.awt.event.ActionEvent evt) {

        }

        private void cbEstadoActionPerformed(java.awt.event.ActionEvent evt) {

        }

        private void configuracionPantalla() {
                this.setTitle("Modificar Préstamo");
                this.setResizable(false);
                this.setLocationRelativeTo(null);

        }

        /**
         * @param args the command line arguments
         */
        public static void main(String args[]) {
                FlatMacDarkLaf.setup();
                EventQueue.invokeLater(() -> new ModificarPrestamo().setVisible(true));
        }

        // Variables declaration - do not modify//GEN-BEGIN:variables
        private javax.swing.JButton btnModificarPrestamo;
        private javax.swing.JButton btnRegresar;
        private javax.swing.JComboBox<String> cbCliente;
        private javax.swing.JComboBox<String> cbEstado;
        private javax.swing.JComboBox<String> cbLibro;
        private javax.swing.JPanel jPanel1;
        private javax.swing.JLabel lbBienvenido;
        private javax.swing.JLabel lbCliente;
        private javax.swing.JLabel lbEstado;
        private javax.swing.JLabel lbFechaDevolucion;
        private javax.swing.JLabel lbFechaPrestamo;
        private javax.swing.JLabel lbLibro;
        private javax.swing.JTextField tfFechaDevolucion;
        private javax.swing.JTextField tfFechaPrestamo;
        // End of variables declaration//GEN-END:variables
}
