// cSpell:ignore alverata configuracion
/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package screens;

import java.awt.Toolkit;

/**
 *
 * @author tutaa
 */
public class ModificarLibro extends javax.swing.JFrame {

	/**
	 * Creates new form Principal
	 */
	public ModificarLibro() {
		initComponents();
		configuracionPantalla();
	}

	/**
	 * This method is called from within the constructor to initialize the
	 * form. WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
	// <editor-fold defaultstate="collapsed" desc="Generated
	// <editor-fold defaultstate="collapsed" desc="Generated
        // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
        private void initComponents() {

                jPanel1 = new javax.swing.JPanel();
                lbModificar = new javax.swing.JLabel();
                lbTitulo = new javax.swing.JLabel();
                tfTitulo = new javax.swing.JTextField();
                lbAutor = new javax.swing.JLabel();
                tfAutor = new javax.swing.JTextField();
                lbGenero = new javax.swing.JLabel();
                cbGenero = new javax.swing.JComboBox<>();
                lbEditorial = new javax.swing.JLabel();
                tfEditorial = new javax.swing.JTextField();
                lbNumeroPaginas = new javax.swing.JLabel();
                tfNumeroPaginas = new javax.swing.JTextField();
                lbIdioma = new javax.swing.JLabel();
                cbIdioma = new javax.swing.JComboBox<>();
                lbSinopsis = new javax.swing.JLabel();
                spSinopsis = new javax.swing.JScrollPane();
                taSinopsis = new javax.swing.JTextArea();
                lbEstado = new javax.swing.JLabel();
                tfEstado = new javax.swing.JTextField();
                lbNumeroCopias = new javax.swing.JLabel();
                tfNumeroCopias = new javax.swing.JTextField();
                btnCrearLibro = new javax.swing.JButton();

                setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

                jPanel1.setBackground(new java.awt.Color(249, 244, 239));
                jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

                lbModificar.setFont(new java.awt.Font("AlverataIrregular-Bold", 0, 50)); // NOI18N
                lbModificar.setForeground(new java.awt.Color(2, 8, 38));
                lbModificar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
                lbModificar.setText("MODIFICAR LIBRO");
                jPanel1.add(lbModificar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 20, 540, -1));

                lbTitulo.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
                lbTitulo.setForeground(new java.awt.Color(2, 8, 38));
                lbTitulo.setText("TÍTULO:");
                jPanel1.add(lbTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 130, 110, -1));

                tfTitulo.setBackground(new java.awt.Color(234, 221, 207));
                tfTitulo.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
                tfTitulo.setForeground(new java.awt.Color(2, 8, 38));
                jPanel1.add(tfTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 130, 210, -1));

                lbAutor.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
                lbAutor.setForeground(new java.awt.Color(2, 8, 38));
                lbAutor.setText("AUTOR:");
                jPanel1.add(lbAutor, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 170, 110, -1));

                tfAutor.setBackground(new java.awt.Color(234, 221, 207));
                tfAutor.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
                tfAutor.setForeground(new java.awt.Color(2, 8, 38));
                jPanel1.add(tfAutor, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 170, 210, -1));

                lbGenero.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
                lbGenero.setForeground(new java.awt.Color(2, 8, 38));
                lbGenero.setText("GÉNERO:");
                jPanel1.add(lbGenero, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 210, 110, -1));

                cbGenero.setBackground(new java.awt.Color(234, 221, 207));
                cbGenero.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
                cbGenero.setForeground(new java.awt.Color(2, 8, 38));
                cbGenero.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Narrativa", "Poesía", "Drama", "Ensayo", "Épica", "Lírica", "Cuento", "Novela", "Fábula", "Mito", "Leyenda", "Autobiografía", "Biografía", "Crónica", "Epopeya", "Sátira", "Oratoria", "Diario", "Epístola", "Tragedia", "Otro" }));
                jPanel1.add(cbGenero, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 210, 210, -1));

                lbEditorial.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
                lbEditorial.setForeground(new java.awt.Color(2, 8, 38));
                lbEditorial.setText("EDITORIAL:");
                jPanel1.add(lbEditorial, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 250, 110, -1));

                tfEditorial.setBackground(new java.awt.Color(234, 221, 207));
                tfEditorial.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
                tfEditorial.setForeground(new java.awt.Color(2, 8, 38));
                jPanel1.add(tfEditorial, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 250, 210, -1));

                lbNumeroPaginas.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
                lbNumeroPaginas.setForeground(new java.awt.Color(2, 8, 38));
                lbNumeroPaginas.setText("NÚMERO PÁGINAS:");
                jPanel1.add(lbNumeroPaginas, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 290, 180, -1));

                tfNumeroPaginas.setBackground(new java.awt.Color(234, 221, 207));
                tfNumeroPaginas.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
                tfNumeroPaginas.setForeground(new java.awt.Color(2, 8, 38));
                jPanel1.add(tfNumeroPaginas, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 290, 130, -1));

                lbIdioma.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
                lbIdioma.setForeground(new java.awt.Color(2, 8, 38));
                lbIdioma.setText("IDIOMA:");
                jPanel1.add(lbIdioma, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 330, 110, -1));

                cbIdioma.setBackground(new java.awt.Color(234, 221, 207));
                cbIdioma.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
                cbIdioma.setForeground(new java.awt.Color(2, 8, 38));
                cbIdioma.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Español", "Inglés", "Mandarín", "Francés", "Árabe", "Ruso", "Alemán", "Japonés", "Hindi", "Portugués", "Italiano", "Coreano", "Bengalí", "Turco", "Persa", "Suajili", "Holandés", "Vietnamita", "Polaco", "Tailandés", "Otro" }));
                jPanel1.add(cbIdioma, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 330, 210, -1));

                lbSinopsis.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
                lbSinopsis.setForeground(new java.awt.Color(2, 8, 38));
                lbSinopsis.setText("SINOPSIS:");
                jPanel1.add(lbSinopsis, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 370, 110, -1));

                taSinopsis.setBackground(new java.awt.Color(234, 221, 207));
                taSinopsis.setColumns(20);
                taSinopsis.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
                taSinopsis.setForeground(new java.awt.Color(2, 8, 38));
                taSinopsis.setRows(5);
                spSinopsis.setViewportView(taSinopsis);

                jPanel1.add(spSinopsis, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 410, 310, 100));

                lbEstado.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
                lbEstado.setForeground(new java.awt.Color(2, 8, 38));
                lbEstado.setText("ESTADO:");
                jPanel1.add(lbEstado, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 530, 110, -1));

                tfEstado.setBackground(new java.awt.Color(234, 221, 207));
                tfEstado.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
                tfEstado.setForeground(new java.awt.Color(2, 8, 38));
                jPanel1.add(tfEstado, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 530, 210, -1));

                lbNumeroCopias.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
                lbNumeroCopias.setForeground(new java.awt.Color(2, 8, 38));
                lbNumeroCopias.setText("NÚMERO COPIAS:");
                jPanel1.add(lbNumeroCopias, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 570, 160, -1));

                tfNumeroCopias.setBackground(new java.awt.Color(234, 221, 207));
                tfNumeroCopias.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
                tfNumeroCopias.setForeground(new java.awt.Color(2, 8, 38));
                jPanel1.add(tfNumeroCopias, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 570, 130, -1));

                btnCrearLibro.setBackground(new java.awt.Color(140, 120, 81));
                btnCrearLibro.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
                btnCrearLibro.setForeground(new java.awt.Color(255, 255, 254));
                btnCrearLibro.setText("Modificar Libro");
                btnCrearLibro.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                btnCrearLibroActionPerformed(evt);
                        }
                });
                jPanel1.add(btnCrearLibro, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 630, -1, -1));

                javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
                getContentPane().setLayout(layout);
                layout.setHorizontalGroup(
                        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 538, javax.swing.GroupLayout.PREFERRED_SIZE)
                );
                layout.setVerticalGroup(
                        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 708, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                );

                pack();
        }// </editor-fold>//GEN-END:initComponents

        private void btnCrearLibroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCrearLibroActionPerformed
                // TODO add your handling code here:
        }//GEN-LAST:event_btnCrearLibroActionPerformed

	private void configuracionPantalla() {
		// TODO: PONER NOMBRE PANTALLA
		this.setTitle("--");
		this.setResizable(false);
		this.setLocationRelativeTo(null);
		// TODO: PONER ICONO APP
		this.setIconImage(Toolkit.getDefaultToolkit()
				.getImage(getClass().getResource("/img/icon.png")));

	}

	private void btnAceptarActionPerformed(java.awt.event.ActionEvent evt) {

	}

	/**
	 * @param args the command line arguments
	 */
	public static void main(String args[]) {
		/* Set the Nimbus look and feel */
		// <editor-fold defaultstate="collapsed" desc=" Look and feel setting code
		// (optional) ">
		/*
		 * If Nimbus (introduced in Java SE 6) is not available, stay with the default
		 * look and feel.
		 * For details see
		 * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
		 */
		try {
			for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
				if ("Nimbus".equals(info.getName())) {
					javax.swing.UIManager.setLookAndFeel(info.getClassName());
					break;
				}
			}
		} catch (ClassNotFoundException ex) {
			java.util.logging.Logger.getLogger(ModificarLibro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (InstantiationException ex) {
			java.util.logging.Logger.getLogger(ModificarLibro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (IllegalAccessException ex) {
			java.util.logging.Logger.getLogger(ModificarLibro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (javax.swing.UnsupportedLookAndFeelException ex) {
			java.util.logging.Logger.getLogger(ModificarLibro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		}
		// </editor-fold>
		// </editor-fold>
		// </editor-fold>
		// </editor-fold>
		// </editor-fold>
		// </editor-fold>
		// </editor-fold>
		// </editor-fold>

		/* Create and display the form */
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				new ModificarLibro().setVisible(true);
			}
		});
	}

        // Variables declaration - do not modify//GEN-BEGIN:variables
        private javax.swing.JButton btnCrearLibro;
        private javax.swing.JComboBox<String> cbGenero;
        private javax.swing.JComboBox<String> cbIdioma;
        private javax.swing.JPanel jPanel1;
        private javax.swing.JLabel lbAutor;
        private javax.swing.JLabel lbEditorial;
        private javax.swing.JLabel lbEstado;
        private javax.swing.JLabel lbGenero;
        private javax.swing.JLabel lbIdioma;
        private javax.swing.JLabel lbModificar;
        private javax.swing.JLabel lbNumeroCopias;
        private javax.swing.JLabel lbNumeroPaginas;
        private javax.swing.JLabel lbSinopsis;
        private javax.swing.JLabel lbTitulo;
        private javax.swing.JScrollPane spSinopsis;
        private javax.swing.JTextArea taSinopsis;
        private javax.swing.JTextField tfAutor;
        private javax.swing.JTextField tfEditorial;
        private javax.swing.JTextField tfEstado;
        private javax.swing.JTextField tfNumeroCopias;
        private javax.swing.JTextField tfNumeroPaginas;
        private javax.swing.JTextField tfTitulo;
        // End of variables declaration//GEN-END:variables
}
