// cSpell:ignore alverata configuracion
/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package screens;

import java.awt.Toolkit;

/**
 *
 * @author tutaa
 */
public class ModificarCliente extends javax.swing.JFrame {

	/**
	 * Creates new form Principal
	 */
	public ModificarCliente() {
		initComponents();
		configuracionPantalla();
	}

	/**
	 * This method is called from within the constructor to initialize the
	 * form. WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
	// <editor-fold defaultstate="collapsed" desc="Generated
	// <editor-fold defaultstate="collapsed" desc="Generated
        // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
        private void initComponents() {

                jPanel1 = new javax.swing.JPanel();
                lbBienvenido = new javax.swing.JLabel();
                lbNombre = new javax.swing.JLabel();
                tfNombre = new javax.swing.JTextField();
                lbDireccion = new javax.swing.JLabel();
                tfDireccion = new javax.swing.JTextField();
                lbTelefono = new javax.swing.JLabel();
                tfTelefono = new javax.swing.JTextField();
                lbEmail = new javax.swing.JLabel();
                tfEmail = new javax.swing.JTextField();
                btnCrearCliente = new javax.swing.JButton();

                setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

                jPanel1.setBackground(new java.awt.Color(249, 244, 239));
                jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

                lbBienvenido.setFont(new java.awt.Font("AlverataIrregular-Bold", 0, 50)); // NOI18N
                lbBienvenido.setForeground(new java.awt.Color(2, 8, 38));
                lbBienvenido.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
                lbBienvenido.setText("MODIFICAR CLIENTE");
                jPanel1.add(lbBienvenido, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 20, 540, -1));

                lbNombre.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
                lbNombre.setForeground(new java.awt.Color(2, 8, 38));
                lbNombre.setText("NOMBRE:");
                jPanel1.add(lbNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 160, 110, -1));

                tfNombre.setBackground(new java.awt.Color(234, 221, 207));
                tfNombre.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
                tfNombre.setForeground(new java.awt.Color(2, 8, 38));
                jPanel1.add(tfNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 160, 210, -1));

                lbDireccion.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
                lbDireccion.setForeground(new java.awt.Color(2, 8, 38));
                lbDireccion.setText("DIRECCIÓN:");
                jPanel1.add(lbDireccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 200, 110, -1));

                tfDireccion.setBackground(new java.awt.Color(234, 221, 207));
                tfDireccion.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
                tfDireccion.setForeground(new java.awt.Color(2, 8, 38));
                jPanel1.add(tfDireccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 200, 210, -1));

                lbTelefono.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
                lbTelefono.setForeground(new java.awt.Color(2, 8, 38));
                lbTelefono.setText("TELÉFONO:");
                jPanel1.add(lbTelefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 240, 110, -1));

                tfTelefono.setBackground(new java.awt.Color(234, 221, 207));
                tfTelefono.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
                tfTelefono.setForeground(new java.awt.Color(2, 8, 38));
                jPanel1.add(tfTelefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 240, 210, -1));

                lbEmail.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
                lbEmail.setForeground(new java.awt.Color(2, 8, 38));
                lbEmail.setText("EMAIL:");
                jPanel1.add(lbEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 280, 110, -1));

                tfEmail.setBackground(new java.awt.Color(234, 221, 207));
                tfEmail.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
                tfEmail.setForeground(new java.awt.Color(2, 8, 38));
                jPanel1.add(tfEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 280, 210, -1));

                btnCrearCliente.setBackground(new java.awt.Color(140, 120, 81));
                btnCrearCliente.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
                btnCrearCliente.setForeground(new java.awt.Color(255, 255, 254));
                btnCrearCliente.setText("Crear Nuevo Cliente");
                btnCrearCliente.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                btnCrearClienteActionPerformed(evt);
                        }
                });
                jPanel1.add(btnCrearCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 370, -1, -1));

                javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
                getContentPane().setLayout(layout);
                layout.setHorizontalGroup(
                        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 538, javax.swing.GroupLayout.PREFERRED_SIZE)
                );
                layout.setVerticalGroup(
                        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 446, javax.swing.GroupLayout.PREFERRED_SIZE)
                );

                pack();
        }// </editor-fold>//GEN-END:initComponents

        private void btnCrearClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCrearClienteActionPerformed
                // TODO add your handling code here:
        }//GEN-LAST:event_btnCrearClienteActionPerformed

	private void configuracionPantalla() {
		// TODO: PONER NOMBRE PANTALLA
		this.setTitle("--");
		this.setResizable(false);
		this.setLocationRelativeTo(null);
		// TODO: PONER ICONO APP
		this.setIconImage(Toolkit.getDefaultToolkit()
				.getImage(getClass().getResource("/img/icon.png")));

	}

	private void btnAceptarActionPerformed(java.awt.event.ActionEvent evt) {

	}

	/**
	 * @param args the command line arguments
	 */
	public static void main(String args[]) {
		/* Set the Nimbus look and feel */
		// <editor-fold defaultstate="collapsed" desc=" Look and feel setting code
		// (optional) ">
		/*
		 * If Nimbus (introduced in Java SE 6) is not available, stay with the default
		 * look and feel.
		 * For details see
		 * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
		 */
		try {
			for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
				if ("Nimbus".equals(info.getName())) {
					javax.swing.UIManager.setLookAndFeel(info.getClassName());
					break;
				}
			}
		} catch (ClassNotFoundException ex) {
			java.util.logging.Logger.getLogger(ModificarCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (InstantiationException ex) {
			java.util.logging.Logger.getLogger(ModificarCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (IllegalAccessException ex) {
			java.util.logging.Logger.getLogger(ModificarCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (javax.swing.UnsupportedLookAndFeelException ex) {
			java.util.logging.Logger.getLogger(ModificarCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		}
		// </editor-fold>
		// </editor-fold>
		// </editor-fold>
		// </editor-fold>

		/* Create and display the form */
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				new ModificarCliente().setVisible(true);
			}
		});
	}

        // Variables declaration - do not modify//GEN-BEGIN:variables
        private javax.swing.JButton btnCrearCliente;
        private javax.swing.JPanel jPanel1;
        private javax.swing.JLabel lbBienvenido;
        private javax.swing.JLabel lbDireccion;
        private javax.swing.JLabel lbEmail;
        private javax.swing.JLabel lbNombre;
        private javax.swing.JLabel lbTelefono;
        private javax.swing.JTextField tfDireccion;
        private javax.swing.JTextField tfEmail;
        private javax.swing.JTextField tfNombre;
        private javax.swing.JTextField tfTelefono;
        // End of variables declaration//GEN-END:variables
}
