// cSpell:ignore alverata configuracion direccion telefono gestion boton operacion
/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package screens;

import javax.swing.JOptionPane;
import java.util.ArrayList;

import java.sql.SQLException;
import classes.OperacionCRUD;
import screens.custom.CambiarIU;
import screens.custom.ObtenerIU;

/**
 *
 * @author tutaa
 */
public class ModificarCliente extends javax.swing.JFrame {

        /**
         * Creates new form Principal
         */
        public ModificarCliente() {
                initComponents();
                configuracionPantalla();
        }

        /**
         * This method is called from within the constructor to initialize the
         * form. WARNING: Do NOT modify this code. The content of this method is
         * always regenerated by the Form Editor.
         */
        @SuppressWarnings("unchecked")
        // <editor-fold defaultstate="collapsed" desc="Generated
        // <editor-fold defaultstate="collapsed" desc="Generated
        // <editor-fold defaultstate="collapsed" desc="Generated
        // <editor-fold defaultstate="collapsed" desc="Generated
        // Code">//GEN-BEGIN:initComponents
        private void initComponents() {

                jPanel1 = new javax.swing.JPanel();
                lbBienvenido = new javax.swing.JLabel();
                btnRegresar = new javax.swing.JButton();
                btnModificarCliente = new javax.swing.JButton();
                lbNombre = new javax.swing.JLabel();
                tfNombre = new javax.swing.JTextField();
                lbDireccion = new javax.swing.JLabel();
                tfDireccion = new javax.swing.JTextField();
                lbTelefono = new javax.swing.JLabel();
                tfTelefono = new javax.swing.JTextField();
                lbEmail = new javax.swing.JLabel();
                tfEmail = new javax.swing.JTextField();

                setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

                jPanel1.setBackground(new java.awt.Color(249, 244, 239));
                jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

                lbBienvenido.setFont(new java.awt.Font("AlverataIrregular-Bold", 0, 50)); // NOI18N
                lbBienvenido.setForeground(new java.awt.Color(2, 8, 38));
                lbBienvenido.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
                lbBienvenido.setText("MODIFICAR CLIENTE");
                jPanel1.add(lbBienvenido, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 20, 540, -1));

                btnRegresar.setBackground(new java.awt.Color(140, 120, 81));
                btnRegresar.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
                btnRegresar.setForeground(new java.awt.Color(255, 255, 254));
                btnRegresar.setText("Regresar");
                btnRegresar.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                btnRegresarActionPerformed(evt);
                        }
                });
                jPanel1.add(btnRegresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 370, -1, -1));

                btnModificarCliente.setBackground(new java.awt.Color(140, 120, 81));
                btnModificarCliente.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
                btnModificarCliente.setForeground(new java.awt.Color(255, 255, 254));
                btnModificarCliente.setText("Modificar Cliente");
                btnModificarCliente.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                btnModificarClienteActionPerformed(evt);
                        }
                });
                jPanel1.add(btnModificarCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 370, -1, -1));

                lbNombre.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
                lbNombre.setForeground(new java.awt.Color(2, 8, 38));
                lbNombre.setText("NOMBRE:");
                jPanel1.add(lbNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 130, 110, -1));

                tfNombre.setBackground(new java.awt.Color(234, 221, 207));
                tfNombre.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
                tfNombre.setForeground(new java.awt.Color(2, 8, 38));
                tfNombre.addKeyListener(new java.awt.event.KeyAdapter() {
                        public void keyReleased(java.awt.event.KeyEvent evt) {
                                tfNombreKeyReleased(evt);
                        }
                });
                jPanel1.add(tfNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 130, 210, -1));

                lbDireccion.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
                lbDireccion.setForeground(new java.awt.Color(2, 8, 38));
                lbDireccion.setText("DIRECCIÓN:");
                jPanel1.add(lbDireccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 170, 110, -1));

                tfDireccion.setBackground(new java.awt.Color(234, 221, 207));
                tfDireccion.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
                tfDireccion.setForeground(new java.awt.Color(2, 8, 38));
                tfDireccion.addKeyListener(new java.awt.event.KeyAdapter() {
                        public void keyReleased(java.awt.event.KeyEvent evt) {
                                tfDireccionKeyReleased(evt);
                        }
                });
                jPanel1.add(tfDireccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 170, 210, -1));

                lbTelefono.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
                lbTelefono.setForeground(new java.awt.Color(2, 8, 38));
                lbTelefono.setText("TELÉFONO:");
                jPanel1.add(lbTelefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 210, 110, -1));

                tfTelefono.setBackground(new java.awt.Color(234, 221, 207));
                tfTelefono.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
                tfTelefono.setForeground(new java.awt.Color(2, 8, 38));
                tfTelefono.addKeyListener(new java.awt.event.KeyAdapter() {
                        public void keyReleased(java.awt.event.KeyEvent evt) {
                                tfTelefonoKeyReleased(evt);
                        }
                });
                jPanel1.add(tfTelefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 210, 210, -1));

                lbEmail.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
                lbEmail.setForeground(new java.awt.Color(2, 8, 38));
                lbEmail.setText("EMAIL:");
                jPanel1.add(lbEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 250, 110, -1));

                tfEmail.setBackground(new java.awt.Color(234, 221, 207));
                tfEmail.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
                tfEmail.setForeground(new java.awt.Color(2, 8, 38));
                tfEmail.addKeyListener(new java.awt.event.KeyAdapter() {
                        public void keyReleased(java.awt.event.KeyEvent evt) {
                                tfEmailKeyReleased(evt);
                        }
                });
                jPanel1.add(tfEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 250, 210, -1));

                javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
                getContentPane().setLayout(layout);
                layout.setHorizontalGroup(
                                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 538,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE));
                layout.setVerticalGroup(
                                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 446,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE));

                pack();
        }// </editor-fold>//GEN-END:initComponents

        private void tfDireccionKeyReleased(java.awt.event.KeyEvent evt) {
                desactivarBotonModificarCliente();

        }

        private void tfTelefonoKeyReleased(java.awt.event.KeyEvent evt) {
                desactivarBotonModificarCliente();

        }

        private void tfEmailKeyReleased(java.awt.event.KeyEvent evt) {
                desactivarBotonModificarCliente();

        }

        private void tfNombreKeyReleased(java.awt.event.KeyEvent evt) {
                desactivarBotonModificarCliente();
        }

        private void btnRegresarActionPerformed(java.awt.event.ActionEvent evt) {
                GestionClientes gc = new GestionClientes();
                gc.setVisible(true);
                this.setVisible(false);

        }

        private void btnModificarClienteActionPerformed(java.awt.event.ActionEvent evt) {
                modificarIdClienteSeleccionado();
                GestionClientes gc = new GestionClientes();
                gc.setVisible(true);
                this.setVisible(false);

        }

        private void configuracionPantalla() {
                this.setTitle("Modificar Cliente");
                this.setResizable(false);
                this.setLocationRelativeTo(null);
                llenarCampos();
                desactivarBotonModificarCliente();
        }

        private void desactivarBotonModificarCliente() {
                boolean camposValidos = ObtenerIU.obtenerLongitudTextoCampo(tfNombre) > 8
                                && ObtenerIU.obtenerLongitudTextoCampo(tfDireccion) > 8
                                && ObtenerIU.obtenerLongitudTextoCampo(tfTelefono) > 8
                                && ObtenerIU.obtenerLongitudTextoCampo(tfEmail) > 15
                                && ObtenerIU.obtenerTextoCampo(tfEmail).contains("@");
                btnModificarCliente.setEnabled(camposValidos);

        }

        private void modificarIdClienteSeleccionado() {
                try {
                        int idClienteModificar = GestionClientes.idClienteSeleccionado;
                        String nombre = ObtenerIU.obtenerTextoCampo(tfNombre);
                        String direccion = ObtenerIU.obtenerTextoCampo(tfDireccion);
                        String telefono = ObtenerIU.obtenerTextoCampo(tfTelefono);
                        String email = ObtenerIU.obtenerTextoCampo(tfEmail);
                        OperacionCRUD.registrar(
                                        String.format("UPDATE clientes SET nombre = '%s', direccion = '%s', telefono = '%s', email = '%s' WHERE id = %d",
                                                        nombre, direccion, telefono, email, idClienteModificar));
                        String nombreClienteRegistrado = String.format("EL CLIENTE %s HA SIDO MODIFICADO CON ÉXITO.",
                                        ObtenerIU.obtenerTextoCampo(tfNombre).toUpperCase());
                        JOptionPane.showMessageDialog(null, nombreClienteRegistrado);
                } catch (SQLException e) {
                        JOptionPane.showMessageDialog(null, e);
                }
        }

        private void llenarCampos() {
                int idClienteModificar = GestionClientes.idClienteSeleccionado;
                ArrayList<ArrayList<Object>> datosCliente;
                try {
                        datosCliente = OperacionCRUD.seleccionar(
                                        "select * from clientes where id= " + idClienteModificar,
                                        new String[] { "nombre", "direccion", "telefono", "email",
                                        });

                        CambiarIU.ponerTextoCampo(tfNombre, String.valueOf(datosCliente.get(0).get(0)));
                        CambiarIU.ponerTextoCampo(tfDireccion, String.valueOf(datosCliente.get(0).get(1)));
                        CambiarIU.ponerTextoCampo(tfTelefono, String.valueOf(datosCliente.get(0).get(2)));
                        CambiarIU.ponerTextoCampo(tfEmail, String.valueOf(datosCliente.get(0).get(3)));
                } catch (SQLException e) {
                        JOptionPane.showMessageDialog(null, e);
                }

        }

        /**
         * @param args the command line arguments
         */
        public static void main(String args[]) {
                /* Set the Nimbus look and feel */
                // <editor-fold defaultstate="collapsed" desc=" Look and feel setting code
                // (optional) ">
                /*
                 * If Nimbus (introduced in Java SE 6) is not available, stay with the default
                 * look and feel.
                 * For details see
                 * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
                 */
                try {
                        for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager
                                        .getInstalledLookAndFeels()) {
                                if ("Nimbus".equals(info.getName())) {
                                        javax.swing.UIManager.setLookAndFeel(info.getClassName());
                                        break;
                                }
                        }
                } catch (ClassNotFoundException ex) {
                        java.util.logging.Logger.getLogger(ModificarCliente.class.getName())
                                        .log(java.util.logging.Level.SEVERE, null, ex);
                } catch (InstantiationException ex) {
                        java.util.logging.Logger.getLogger(ModificarCliente.class.getName())
                                        .log(java.util.logging.Level.SEVERE, null, ex);
                } catch (IllegalAccessException ex) {
                        java.util.logging.Logger.getLogger(ModificarCliente.class.getName())
                                        .log(java.util.logging.Level.SEVERE, null, ex);
                } catch (javax.swing.UnsupportedLookAndFeelException ex) {
                        java.util.logging.Logger.getLogger(ModificarCliente.class.getName())
                                        .log(java.util.logging.Level.SEVERE, null, ex);
                }
                // </editor-fold>
                // </editor-fold>
                // </editor-fold>
                // </editor-fold>

                /* Create and display the form */
                java.awt.EventQueue.invokeLater(new Runnable() {
                        public void run() {
                                new ModificarCliente().setVisible(true);
                        }
                });
        }

        // Variables declaration - do not modify//GEN-BEGIN:variables
        private javax.swing.JButton btnModificarCliente;
        private javax.swing.JButton btnRegresar;
        private javax.swing.JPanel jPanel1;
        private javax.swing.JLabel lbBienvenido;
        private javax.swing.JLabel lbDireccion;
        private javax.swing.JLabel lbEmail;
        private javax.swing.JLabel lbNombre;
        private javax.swing.JLabel lbTelefono;
        private javax.swing.JTextField tfDireccion;
        private javax.swing.JTextField tfEmail;
        private javax.swing.JTextField tfNombre;
        private javax.swing.JTextField tfTelefono;
        // End of variables declaration//GEN-END:variables
}
