// cSpell:ignore alverata configuracion gestion
/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package screens;

import com.formdev.flatlaf.themes.FlatMacDarkLaf;

import screens.custom.CambiarIU;
import java.awt.EventQueue;
//TODO: CAMBIAR BASE DE DATOS, ELIMINAR CAMPOS INNECESARIOS

/**
 *
 * @author tutaa
 */
public class Principal extends javax.swing.JFrame {

        /**
         * Creates new form Principal
         */
        public Principal() {
                initComponents();
                configuracionPantalla();
        }

        /**
         * This method is called from within the constructor to initialize the
         * form. WARNING: Do NOT modify this code. The content of this method is
         * always regenerated by the Form Editor.
         */
        @SuppressWarnings("unchecked")
        // <editor-fold defaultstate="collapsed" desc="Generated
        // <editor-fold defaultstate="collapsed" desc="Generated
        // <editor-fold defaultstate="collapsed" desc="Generated
        // Code">//GEN-BEGIN:initComponents
        private void initComponents() {

                jPanel1 = new javax.swing.JPanel();
                lbBienvenido = new javax.swing.JLabel();
                Dashboard = new javax.swing.JPanel();
                imgCustomers = new javax.swing.JLabel();
                imgBooks = new javax.swing.JLabel();
                ImgLendings = new javax.swing.JLabel();
                imgWelcome = new javax.swing.JLabel();

                setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

                jPanel1.setBackground(new java.awt.Color(249, 244, 239));
                jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

                lbBienvenido.setFont(new java.awt.Font("AlverataIrregular-Bold", 0, 80)); // NOI18N
                lbBienvenido.setForeground(new java.awt.Color(2, 8, 38));
                lbBienvenido.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
                lbBienvenido.setText("BIENVENIDO");
                jPanel1.add(lbBienvenido, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 20, 850, -1));

                Dashboard.setBackground(new java.awt.Color(234, 221, 207));
                Dashboard.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

                imgCustomers.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/img/customers.png"))); // NOI18N
                imgCustomers.setToolTipText("Clientes");
                imgCustomers.addMouseListener(new java.awt.event.MouseAdapter() {
                        public void mouseClicked(java.awt.event.MouseEvent evt) {
                                imgCustomersMouseClicked(evt);
                        }

                        public void mouseEntered(java.awt.event.MouseEvent evt) {
                                imgCustomersMouseEntered(evt);
                        }

                        public void mouseExited(java.awt.event.MouseEvent evt) {
                                imgCustomersMouseExited(evt);
                        }
                });
                Dashboard.add(imgCustomers, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 10, 50, 50));

                imgBooks.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/img/books.png"))); // NOI18N
                imgBooks.setToolTipText("Libros");
                imgBooks.addMouseListener(new java.awt.event.MouseAdapter() {
                        public void mouseClicked(java.awt.event.MouseEvent evt) {
                                imgBooksMouseClicked(evt);
                        }

                        public void mouseEntered(java.awt.event.MouseEvent evt) {
                                imgBooksMouseEntered(evt);
                        }

                        public void mouseExited(java.awt.event.MouseEvent evt) {
                                imgBooksMouseExited(evt);
                        }
                });
                Dashboard.add(imgBooks, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 10, 50, 50));

                ImgLendings.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/img/lendings.png"))); // NOI18N
                ImgLendings.setToolTipText("Prestamos");
                ImgLendings.addMouseListener(new java.awt.event.MouseAdapter() {
                        public void mouseClicked(java.awt.event.MouseEvent evt) {
                                ImgLendingsMouseClicked(evt);
                        }

                        public void mouseEntered(java.awt.event.MouseEvent evt) {
                                ImgLendingsMouseEntered(evt);
                        }

                        public void mouseExited(java.awt.event.MouseEvent evt) {
                                ImgLendingsMouseExited(evt);
                        }
                });
                Dashboard.add(ImgLendings, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 10, 50, 50));

                jPanel1.add(Dashboard, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 480, 850, 60));

                imgWelcome.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
                imgWelcome.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/img/welcome.png"))); // NOI18N
                jPanel1.add(imgWelcome, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 90, 850, -1));

                javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
                getContentPane().setLayout(layout);
                layout.setHorizontalGroup(
                                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 852,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE));
                layout.setVerticalGroup(
                                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 542,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE));

                pack();
        }// </editor-fold>//GEN-END:initComponents

        private void imgCustomersMouseEntered(java.awt.event.MouseEvent evt) {
                CambiarIU.setImageLabel(imgCustomers, "src/resources/img/customersHover.png");

        }

        private void imgCustomersMouseExited(java.awt.event.MouseEvent evt) {
                CambiarIU.setImageLabel(imgCustomers, "src/resources/img/customers.png");

        }

        private void imgCustomersMouseClicked(java.awt.event.MouseEvent evt) {
                GestionClientes gc = new GestionClientes();
                gc.setVisible(true);
                this.setVisible(false);

        }

        private void imgBooksMouseEntered(java.awt.event.MouseEvent evt) {
                CambiarIU.setImageLabel(imgBooks, "src/resources/img/BooksHover.png");
        }

        private void imgBooksMouseExited(java.awt.event.MouseEvent evt) {
                CambiarIU.setImageLabel(imgBooks, "src/resources/img/Books.png");
        }

        private void imgBooksMouseClicked(java.awt.event.MouseEvent evt) {
                GestionLibros gl = new GestionLibros();
                gl.setVisible(true);
                this.setVisible(false);

        }

        private void ImgLendingsMouseEntered(java.awt.event.MouseEvent evt) {
                CambiarIU.setImageLabel(ImgLendings, "src/resources/img/LendingsHover.png");

        }

        private void ImgLendingsMouseExited(java.awt.event.MouseEvent evt) {
                CambiarIU.setImageLabel(ImgLendings, "src/resources/img/Lendings.png");

        }

        private void ImgLendingsMouseClicked(java.awt.event.MouseEvent evt) {
                GestionPrestamos gp = new GestionPrestamos();
                gp.setVisible(true);
                this.setVisible(false);

        }

        private void configuracionPantalla() {
                this.setTitle("Principal");
                this.setResizable(false);
                this.setLocationRelativeTo(null);
        }

        /**
         * @param args the command line arguments
         */
        public static void main(String args[]) {
                FlatMacDarkLaf.setup();
                EventQueue.invokeLater(() -> new Principal().setVisible(true));
        }

        // Variables declaration - do not modify//GEN-BEGIN:variables
        private javax.swing.JPanel Dashboard;
        private javax.swing.JLabel ImgLendings;
        private javax.swing.JLabel imgBooks;
        private javax.swing.JLabel imgCustomers;
        private javax.swing.JLabel imgWelcome;
        private javax.swing.JPanel jPanel1;
        private javax.swing.JLabel lbBienvenido;
        // End of variables declaration//GEN-END:variables
}
